<a href="https://colab.research.google.com/github/Aboelsaood23/Aboelsaood23/blob/main/Deep_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**NumPy Library :**
   it is a Python library for numerical computing that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

  NumPy's importance in neural networks lies in its fundamental role in handling data efficiently. Here's why NumPy is crucial for neural networks:
*   Efficient numerical computations
*   Array operations
*   Integration with deep learning frameworks
*   Compatibility with scientific computing libraries

##**Sigmoid Function:**
*   The sigmoid function, often denoted as σ(x), is a mathematical function that maps any real-valued number to a value between 0 and 1. It has an S-shaped curve and is widely used in various fields
*   working with NumPy arrays, np.exp() is generally preferable to math.exp(), for several reasons :
   1.   Broadcasting
   2.   Performance
   3.   *Consistency*

In [12]:
import math
import numpy as np
def basic_sigmoid(x):
  s =1/(1+math.exp(-x))
  return s
#check performance of the basic function
print("basic sigmoid function using math.exp = ",basic_sigmoid(3) )

#we rarely use the "math" library in deep learning because the inputs of the functions are real numbers.
#In deep learning we mostly use matrices and vectors

x =np.array([1,2,3]) # this array can't be passed to basic sigmoid function that uses math.exp()
def sigmoid(x):
  s =1/(1+np.exp(-x))
  return s
#check performance of this function
print("sigmoid of new x :",sigmoid(x))



basic sigmoid function using math.exp =  0.9525741268224334
sigmoid of new x : [0.73105858 0.88079708 0.95257413]


###**Sigmoid derivative :**
*   will be used on gradient functions and to optimize loss function = sigmoid(x)(1-sigmoid(x))



In [13]:
def derivative_sigmoid(x):
  s = sigmoid(x) #calling sigmoid function
  ds= s*(1-s)
  return s

print("sigmoid derivative df x = ",derivative_sigmoid(x))

sigmoid derivative df x =  [0.73105858 0.88079708 0.95257413]


###**Reshaping arrays using numpy :**
*   Two common numpy functions used in deep learning are np.shape and np.reshape().
* X.shape is used to get the shape (dimension) of a matrix/vector X.
* X.reshape(...) is used to reshape X into some other dimension.




In [14]:
#Implement image2vector() that takes an input of shape (length, height, 3) and returns a vector of shape (length*height*3, 1).
def image2vector(image):
  v =image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
  return v

#check performance of this function
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print("\nshape of original image",image.shape)
print("shape of reshaped image",image2vector(image).shape)
print("new reshaped image",image2vector(image))



shape of original image (3, 3, 2)
shape of reshaped image (18, 1)
new reshaped image [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


###**Normalizing rows using numpy :**
*   Another common technique we use in Machine Learning and Deep Learning is to normalize our data.
* It often leads to a better performance because gradient descent converges faster after normalization.
* by normalization we mean changing x to x/||x|| (dividing each row vector of x by its norm).
* x_norm takes the norm of each row of x. So x_norm has the same number of rows but only 1 column,So how did it work when you divided x by x_norm? This is called broadcasting

In [15]:
def normalizeRows(x):
  x_norm =np.linalg.norm(x,axis=1,keepdims =True)
  #axis=1 means that the norm is calculated along the second axis,So, the norm is calculated for each row of the array.
  #keepdims = True : This parameter, when set to True, ensures that the dimensions of the output are the same as the input
  x =x/x_norm
  return x

#check performance of this function
x =np.array([
    [0,3,4],
    [1,6,4]
])
print("normalizeRows(x)= "+str(normalizeRows(x)))
print("shape before noermalization",x.shape)
print("shape after normalization",normalizeRows(x).shape)



normalizeRows(x)= [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]
shape before noermalization (2, 3)
shape after normalization (2, 3)


###**softmax using numpy :**
*   it a popular activation function used in neural networks, particularly in the output layer for multi-class classification tasks
*  It takes a vector of real numbers as input and outputs a probability distribution over multiple classes, ensuring that the sum of the probabilities adds up to 1.

In [16]:
def softmax(x):
  x_exp =np.exp(x)
  x_sum =np.sum(x_exp,axis =1,keepdims=True)
  s =x_exp/x_sum
  return s

#check performance of this function
x =np.array([[9,2,5,0,0],
             [7,5,0,0,0]])
print("softmax(x) = "+str(softmax(x)))


softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


###**Vectorization usnig NumPy :**
*   technique used in computer programming and numerical computing to perform operations on entire arrays or vectors of data at once, rather than on individual elements sequentially
* we will implement three operations to check differnce on performance using victorizations and normal implementation :
   1. DOT PRODUCT :  multiply each elemnent by corresponding element, then do summation for all results
   2. OUTER PRODUCT : multiply each element on x1 to all elements of x2, then move to next element and so on
   3. ELEMENTWISE : multiply each element on crossponding element of x2

In [31]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

#classic dot product
tic =time.process_time()
dot =0
for i in range(len(x1)):
  dot = x1[i]*x2[i]
toc =time.process_time()
print("dot = "+str(dot)+"\n computation time for classic dot product ="+str(1000*(toc-tic))+"ms")


#classic outer product
tic =time.process_time()
outer =np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
  for j in range(len(x2)):
    outer[i,j] =x1[i]*x2[i]

toc =time.process_time()
print("\n\nouter : "+str(outer)+"\ncomputation time for classic outer product"+str(1000*(toc-tic))+"ms")


#classi element wise
tic =time.process_time()
mul =np.zeros(len(x1))
for i in range(len(x1)):
  mul[i] =x1[i]*x2[i]
toc =time.process_time()
print("\n\nelementwie multiplication = "+str(mul)+"\n computation time for classic elemnetwise "+str(1000*(toc-tic))+"ms")


#Do all sam operations using vectoriation
print("\n\nVectorized Resluts")
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

#dot product
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("\n\ndot = " + str(dot) + "\nComputation time for dot product vectorized = " + str(1000*(toc - tic)) + "ms")

#Outer product
tic  =time.process_time()
outer=np.outer(x1,x2)
toc  =time.process_time()
print("\n\nelementwise multiplication ="+str(mul)+"\n computation time for outer product vectorized ="+str(1000*(toc-tic))+"ms")

#elementwise
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("\n\nelementwise multiplication = " + str(mul) + "\ncomputation time for elementwise vectorized = " + str(1000*(toc - tic)) + "ms")


dot = 0
 computation time for classic dot product =0.18673400000324136ms


outer : [[81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 63. 63. 63. 63. 63. 63. 63. 63. 63. 63. 63. 63. 63. 63.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81. 81.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  